services:
  taas.app:
    env_file:
      - .env
    build:
      context: "."
      dockerfile: "dockerfile.app.${APP_ENV}"
      args:
        - APP_PORT=${APP_PORT}
    container_name: taas.app
    restart: unless-stopped
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - COMPOSE_BAKE=true
    networks:
      - taas-network

  taas.ollama:
    env_file:
      - .env
    build:
      context: "."
      dockerfile: "dockerfile.ollama"
      args:
        - OLLAMA_LLM_MODEL=${OLLAMA_LLM_MODEL}
        - OLLAMA_EMBEDDING_MODEL=${OLLAMA_EMBEDDING_MODEL}
    container_name: taas.ollama
    restart: unless-stopped
    ports:
      - "${OLLAMA_PORT}:11434"
    volumes:
      - ollama:/root/.ollama
    networks:
      - taas-network

networks:
  taas-network:
    driver: bridge

volumes:
  ollama:
